version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t my-dockerhub-username/my-docker-image .
      - run:
          name: Log in to Docker Hub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Push Image to Docker Hub
          command: docker push my-dockerhub-username/my-docker-image

workflows:
  version: 2
  build_and_push:
    jobs:
      - build

