version: 2.1

orbs:
  docker: circleci/docker@2.4.0

jobs:
  build_and_test:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout

      # Build the Docker image using the Docker orb
      - docker/build:
          image: $DOCKERHUB_USERNAME/nodecicd
          tag: latest

      - docker/auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

      # Push the Docker image using the Docker orb (only if tests pass)
      - docker/push:
          image: $DOCKERHUB_USERNAME/nodecicd
          tag: latest

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build_and_test


