version: 2.1

orbs:
  docker: circleci/docker@2.4.0

jobs:
  build_and_test:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout

      # Build the Docker image using the Docker orb
      - docker/build:
          image: $DOCKERHUB_USERNAME/nodecicd
          tag: latest

      # Run the container
      - run:
          name: Run Docker Container
          command: docker run -d -p 8080:8080 --name test-container $DOCKERHUB_USERNAME/nodecicd:latest

      # Wait for the service to start
      - run:
          name: Wait for Service to Start
          command: sleep 5

      # Push the Docker image using the Docker orb (only if tests pass)
      - docker/publish:
          image: $DOCKERHUB_USERNAME/nodecicd
          tag: latest

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build_and_test


